name: CI

# Only triggers on pushes/PRs to master
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - github_actions

jobs:
  test:
    name: Unittests
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-latest, ldc-latest]
        arch: [x86_64]
        tests: [unittests]
        include:
          - { os: windows-latest, dc: dmd-2.092.0, arch: x86_64, tests: unittests }
          - { os: windows-latest, dc: dmd-2.092.0, arch: x86_mscoff, tests: unittests }
          - { os: windows-latest, dc: dmd-2.091.1, arch: x86_64, tests: unittests }
          - { os: windows-latest, dc: ldc-1.20.1, arch: x86_64, tests: unittests }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ${{ matrix.dc }}

      - name: Run tests
        env:
          ARCH: ${{matrix.arch}}
          TESTS: ${{matrix.tests}}
        run: ./test.sh
        shell: bash

  vibe-d:
    name: vibe.d
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-latest, ldc-latest]
        arch: [x86_64]
        tests: [vibe-d]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
            compiler: ${{ matrix.dc }}

      - name: Run tests
        env:
          ARCH: ${{matrix.arch}}
          TESTS: ${{matrix.tests}}
        run: ./test.sh
        shell: bash
