name: Run all D Tests

# Only triggers on pushes/PRs to master
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - github_actions

jobs:
    test:
        name: Dub Tests
        timeout-minutes: 30
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, windows-latest, macOS-latest]
                dc: [dmd-latest, ldc-latest]
                arch: [x86_64]
                include:
                  - { os: windows-latest, dc: dmd-2.092.0, arch: x86_64 }
                  - { os: windows-latest, dc: dmd-2.092.0, arch: x86_mscoff }
                  - { os: windows-latest, dc: dmd-2.091.1, arch: x86_64 }
                  - { os: windows-latest, dc: ldc-1.20.1, arch: x86_64 }

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3

            - name: Install D compiler
              uses: dlang-community/setup-dlang@v1
              with:
                  compiler: ${{ matrix.dc }}

            - name: Run tests
              run: dub test -a ${{matrix.arch}}
              shell: bash
